### ISSUE TITLE
Provide warning in README or program, that exact path of CSV must be provided

### ISSUE THREAD

**Issue by Riveascore** [AndiH/alfred-snippets#2]
## Summary

If I try to run using a relative path `./a_text_exports/Default.csv`, I get an error (posted at bottom).

I have to use the exact path:
`/Users/USER/Downloads/alfred-snippets-master/a_text_exports/Default.csv`

So it might be worth mentioning in the README, or just allow relative path inputs.

## Full Error:

```py
/Users/USER/Downloads/alfred-snippets-master/./convert-aText-to-Alfred.py:27: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  tempdict["name"] = entry[2] if entry[2] is not "" else entry[0][1:]
Traceback (most recent call last):
  File "/Users/USER/Downloads/alfred-snippets-master/./convert-aText-to-Alfred.py", line 68, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/USER/Downloads/alfred-snippets-master/./convert-aText-to-Alfred.py", line 61, in main
    with zipfile.ZipFile(outputFilename, "w", zipfile.ZIP_DEFLATED) as zf:
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: './a_text_exports/Default.alfredsnippets'
```

**Comment by AndiH** [comment]
The project is stale since 7 years and I haven't used it since. If you think the comment would improve the README, I'm glad to merge a pull request!
